apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
    services: demo-db
spec:
  selector:
    matchLabels:
      app: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - image: localhost:5000/apps/demo
        name: app
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Dspring.profiles.active=mysql
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 4000m
        volumeMounts:
        - name: binding
          mountPath: /bindings/demo-db
          readOnly: true
      volumes:
      - name: binding
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: demo-db
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: petclinic