# Only needed in TAP up to v1.6 when Rabbit or MySQL coontrollers are used
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: crossplane-kubernetes-provider-secretimport-read-writer
 labels:   
   services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups: ["secretgen.carvel.dev"]
  resources: ["secretimports"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: crossplane-kubernetes-provider-rmq-read-writer
 labels:
   services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups: ["rabbitmq.com"]
  resources: ["rabbitmqclusters"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: crossplane-kubernetes-provider-mysql-read-writer
 labels:
   services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups: ["with.sql.tanzu.vmware.com"]
  resources: ["mysqls"]
  verbs: ["*"]